services:
  db:
    image: 
      postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gameLibraryDB
    volumes:
       - postgres_data:/var/lib/postgresql/data
       - ./db/init:/docker-entrypoint-initdb.d
  api:
    build: .
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_NAME: gameLibraryDB
    ports:
      - 8081:8080

volumes:
  postgres_data:
